Copyright = "<br></br>  All rights reserved - 2019"
LanguageCode = "fr-FR"
Title = "The Law Offices of Joseph A. Bondy"
baseURL = "/"
canonifyurls = true
paginate = 5
[[menu.main]]
identifier = "Contact Us"
name = "- Contactus "
pre = "<h3>Contact Us</h3>"
url = "/contact_us/"
weight = 1
[[menu.main]]
identifier = "Media"
name = "- ITK420 "
pre = "<h3> Media <h3>"
url = "/itk420/"
weight = 2
[[menu.main]]
identifier = "Practice Areas"
name = "- Cannabis Law "
pre = ""
url = "/cannabis_law/"
weight = 3
[[menu.main]]
identifier = ""
name = "- Criminal Defense "
pre = "<h3>Practice Areas</h3>"
url = "/criminal_defense/"
weight = 4
[[menu.main]]
identifier = ""
name = "- Testimonials "
pre = ""
url = "/client_testimonials/"
weight = 5
[[menu.main]]
identifier = ""
name = "- Significant Cases "
pre = ""
url = "/significant_cases/"
weight = 6
[[menu.main]]
identifier = "About The Firm"
name = "- Attorneys "
pre = "<h3>About the Firm</h3>"
url = "/attorneys/"
weight = 7
[params]
author = "Joseph A. Bondy"
authorbio = "Joseph A. Bondy is a criminal defense and corporate cannabis attorney in Manhattan. A graduate of Columbia University and Brooklyn Law School, Mr. Bondy is admitted to practice in New York, the United States District Courts for the Northern, Southern, Eastern and Western Districts of New York, the District of Connecticut, the United States Courts of Appeal for the First, Second, Third, and Fourth Circuits, and the Supreme Court of the United States. Over the past twenty-four years, he has represented more than one thousand individuals at all stages of litigation, including dozens of federal and state cannabis clients. "
authorlocation = "1776 Broadway Suite 2000 NewYork, NY 10019"
authorwebsite = "/"
cover = "images/c14.jpg"
description = "Joseph A. Bondy is a criminal defense and corporate cannabis lawyer in private practice in New York. Mr. Bondy defends all types of criminal cases, from initial arrest through grand jury investigation, pre-trial discovery and motions, trial, sentencing and appeals, in both the federal and state courts, and represents a number of companies in the cannabis and industrial hemp industry on a variety of corporate and securities law matters. Mr. Bondy is admitted to practice in the State of New York, the United States District Courts for the Northern, Southern, Eastern and Western Districts of New York, the District District of Connecticut, the United States Court of Appeals for the First, Second, Third, and Fourth Circuits, and the Supreme Court of the United States."
googleAnalyticsUserID = "UA-79101-12"
hideHUGOSupport = true
hjsStyle = "default"
logo = "images/jab_profilepic_alt.png"
metadescription = "Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead"
